#!/bin/env php 
<?php 
$frameworks[1]['laravel'] = 'laravel/laravel';
$frameworks[2]['silverstripe'] = 'silverstripe/installer';

foreach ($frameworks as $i => $fw) {
    echo "[".($i)."] ".(key($fw)) . "\r\n";
}
echo "Enter the for the framework above: ";
$handle = fopen ("php://stdin","r");
$framework = current($frameworks[fgets($handle)]);
print_r($framework);

echo "installing $framework software...\n";

if(!file_exists("server/app")){
    echo "...Laravel...\n";
    file_exists("vendor/$framework/") or shell_exec("composer require $framework");
    echo "..Server...\n";
    !file_exists("server") or shell_exec("rm -rf server");
    shell_exec("mv vendor/$framework/ ./server ");
    echo "...Public...\n";
    !file_exists("public") || shell_exec("rm -rf public");
    shell_exec("mv server/public ./ ");
    echo "...Client...\n";
    !file_exists("client") || shell_exec("rm -rf client");
    shell_exec("mv server/resources/ ./client ");

    shell_exec("rm -rf $framework/{*.,.,}*");
    shell_exec("composer replace $framework");
    shell_exec("composer require laravel/framework");

    $index = "public/index.php";
    
    file_put_contents($index, str_replace(
        __DIR__."/../bootstrap/app.php",
        __DIR__."/../server/bootstrap/app.php",
        file_get_contents($index)));
} 